language: java
jdk:
  - oraclejdk8
services:
  - mysql
before_script:
  - mysql -e 'create database bank_testdb;'
  - mysql -u travis bank_testdb < schemas/bank_ddl.sql
after_script:
  - mysql -e 'drop database bank_testdb;'
